version: '3.8'
services:
  db:
    image: postgres:15.3-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: bookingdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # datalari davamli saxlamaq ucun
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
