spring:
  application:
    name: ms-reservation
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookingdb
    username: pass
    password: 1212
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false # DB ilə iş bitdikdə session bağlanır
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9094
  servlet:
    session:
      timeout: 30

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

